# Generated by Django 4.1.10 on 2023-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("blog_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("audio_path", models.CharField(max_length=255)),
                ("file_size", models.FloatField()),
                ("view", models.IntegerField()),
                ("date_create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
