# Generated by Django 4.1.10 on 2023-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="picUrl",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
    ]
